#!/bin/bash

BASE_SCRIPT=/usr/lib/steamos/gamescope-session
EGPU_SCRIPT=/tmp/gamescope-session-egpu

if [ -n "$VULKAN_ADAPTER" ]; then
    printf '%s\n%s\n' "$(<$BASE_SCRIPT)" "    --prefer-vk-device $VULKAN_ADAPTER \\" > "$EGPU_SCRIPT"
else
    cp "$BASE_SCRIPT" "$EGPU_SCRIPT"
fi

source "$EGPU_SCRIPT"
